version: "3.2"

#volumes:
#  pg_volume:

services:
    hospital_service:
      image: alekckorsh/hospital:latest
      restart: always
      container_name: application
      ports:
      - 8085:8085
      environment:
        POSTGRES_HOST: postgresdb
      links:
        - postgresdb



    postgresdb:
      image: postgres:latest
      restart: always
      container_name: postgres
      environment:
        POSTGRES_DB: "hospital"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"
      volumes:
          - ./pg_data:/var/lib/postgres/data/pgdata
      ports:
        - 5432:5432

