version: "2.3"

volumes:
  pg_volume:

services:
    hospital_service:
      image: alekckorsh/hospital:latest
      restart: always
      ports:
      - 8085:8085
      environment:
        POSTGRES_PORT: 5432
        POSTGRES_DB: "hospital"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"



#    postgres_db:
#      image: postgres:latest
#      restart: always
#      environment:
#        POSTGRES_DB: "hospital"
#        POSTGRES_USER: "postgres"
#        POSTGRES_PASSWORD: "root"
#        volumes:
#          -pg_volume:/var/lib/postgresql/data
#      ports:
#        - ${POSTGRES_PORT:-5432}:5432

